python/python_web/djangoProject/APP03/urls.py
from django.urls import path

from APP03 import views

app_name = 'APP03'  # 应用名空间 ,在反向定位时用到了

urlpatterns = [
    path('register/', views.register, name='register'),
    path('form/', views.form, name='form'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('email/', views.email, name='email'),
    path('artical/', views.artical, name='artical'),
    path('uploads/', views.uploads, name='uploads'),
]

python/python_web/djangoProject/App/urls.py
from django.urls import path

from App import views

app_name = 'App'  # 应用名空间 ,在反向定位时用到了

urlpatterns = [
    path('home/', views.home, name='home'),
    path('main_app/', views.main_app, name='main_app'),
    path('main_app/<int:id>/', views.main_app, name='main_app'),
    path('main_app2/', views.main_app2, name='main_app2'),
    path('send_message/', views.send_message, name='send_message'),
]

python/python_web/djangoProject/App04/urls.py
from django.urls import path

from App04 import views

app_name = 'App04'  # 应用名空间 ,在反向定位时用到了

urlpatterns = [
    path('', views.index, name='index'),
    path('setcache/', views.SetCache, name='setcache'),
    path('checkuser/', views.checkUser, name='checkUser'),
    path('activeuser/<path:token>/', views.activeuser, name='activeuser'),

]

python/python_web/djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('user/', include('App.urls')),
    path('app/', include('App02.urls')),
    path('register/', include('APP03.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    path('cache/', include('App04.urls')),

]

python/python_web/djangoProject/templates/active.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>尊敬的用户 {{ username }}：</p>
<p> &nbsp;&nbsp;&nbsp;&nbsp;你玩的游戏贪婪玩月账号已被封禁，<a href="http://www.baidu.com">请点击解封</a>
</p>
<p>谢谢</p>
</body>
</html>

python/python_web/djangoProject/templates/artical.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="/static/tinymce/tinymce.min.js"></script>
    <script>

        tinyMCE.init({
            'mode': 'textareas',
            'width': 800,
            'height': 600
        })

    </script>
    <title>Document</title>
</head>
<body>
<form action="{% url 'APP03:artical' %}" method="post">

    {% csrf_token %}
    <textarea name="content" id="" cols="30" rows="10"></textarea>
    <input type="submit">
</form>
</body>
</html>

python/python_web/djangoProject/templates/checkUser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'App04:checkUser' %}" method="post">
    {% csrf_token %}
    邮箱：<input type="text" name="email"> <br>
    用户名：<input type="text" name="username"> <br>
    密码：<input type="text" name="password"> <br>
    <input type="submit" value="提交">
</form>
</body>
</html>

python/python_web/djangoProject/templates/email_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>尊敬的用户您好</p>
<p>请点击下方链接激活账号</p>
<a href="{{ url }}">激活链接</a>
{#<a href="http://www.baidu.com">激活链接</a>#}

</body>
</html>

python/python_web/djangoProject/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
    <style>
        *{
            list-style: none;
            margin: 0;
            padding: 0;
        }
        body,html{
            width: 100%;
            height: 100%;
        }
        .home{
            width: 100%;
            height: 100%;
            background: #ccc;
            display: flex;
            justify-content: flex-start;
            align-items: center;
        }

        .left{
            flex: 1;
            height: 100%;
            flex-shrink: 0;
            background: aqua;
        }
        .main{
            flex: 4;
            background: skyblue;
            height: 100%;
            display: flex;
            flex-direction: column;
            justify-content: flex-start;
            align-items: center;
        }
        .main .header{
            width: 100%;
            flex: 1;
        }
        .main .app{
            width: 100%;
            flex: 9;
            background: #fff;
        }
    </style>
</head>
<body>
    <div class="home">

        <div class="left">
            <a href="{% url 'App:main_app2' %}" target="main_app">点击跳转</a>
        </div>
        <div class="main">
            <div class="header">
                <h1>这是header头部</h1>
            </div>
            <div class="app">
                <iframe src="/user/main_app" frameborder="0" width="100%" height="100%" name="main_app"></iframe>
            </div>
        </div>

    </div>
</body>
</html>

python/python_web/djangoProject/templates/home1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>首页</h1>
{% csrf_token %}
{% if username %}
    {{ username }}
    {{ is_login }}

{% else %}
    还未登陆
{% endif %}

<a href="{% url 'APP03:logout' %}?logout=1" name="logout"> 退出登录</a>
</body>
</html>

python/python_web/djangoProject/templates/index.html
{% load cache %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>cache</title>
</head>
<body>
{% cache 10 'current_time' %}
    {{ current_time }}
{% endcache %}
<br>

{{ pre_time }}
</body>
</html>

python/python_web/djangoProject/templates/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="{% url 'APP03:login' %}" method="post">
    {% csrf_token %}
    用户名： <input type="text" name="username"> <br>
    密码： <input type="text" name="password"> <br>
    {{ form.captcha.errors }}
    <div class="field">
        <div class="ui left img input">
            <button id='js-captcha-refresh' class='ui icon button '><i class="refresh icon green"></i></button>
            <img src="{{ image_url }}" alt="captcha" class="captcha">
            <input autocomplete="off" id="id_captcha_1" name="captcha_1" type="text" placeholder="输入验证码">
            <input id="id_reg_captcha_0" name="captcha_0" type="hidden" value="{{ hashkey }}">
        </div>
    </div>
    <input type="submit">
</form>
<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.js"></script>
<script>
    $('.captcha').click(function () {
        $.getJSON("/captcha/refresh/", function (result) {
            $('.captcha').attr('src', result['image_url']);
            $('#id_captcha_0').val(result['key'])
        });

    });
</script>
</body>
</html>

python/python_web/djangoProject/templates/main_app.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>main_app</title>
    <style>
        html, body {
            width: 100%;
            height: 100%;
        }

        * {
            margin: 0;
            padding: 0;
            list-style: none;
            box-sizing: border-box;
        }

        .home {
            width: 100%;
            height: 100%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: flex-start;
        }

        .tab {
            flex: 1;
            flex-shrink: 0;
            width: 100%;
            display: flex;
            justify-content: flex-start;
            align-items: center;
        }

        .main1 {
            flex: 7;
            width: 100%;
            padding: 10px;
        }

        .main1 ul li {
            display: flex;
            justify-content: flex-start;
            align-items: center;
            padding: 10px;
        }

        .tab ul {
            display: flex;
            justify-content: flex-start;
            align-items: center;
            width: 100%;
        }

        .tab ul li {
            padding: 30px;
            margin: 0 10px 0 10px;
            background: #ccc;

        }

        .tab ul li:nth-child(1) {
            margin-left: 20px;
        }

        .tab ul li:hover {
            background: skyblue;
            transition: all 0.3s ease;
        }

        a {
            text-decoration: none;
            color: black;
        }


    </style>
</head>
<body>
<div class="home">
    <div class="tab">
        <ul>
            {% for i in artic_tab %}
                <li>
                    <a href="{% url 'App:main_app' id=i.id %}" target="main_app">{{ i.tab }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="main1">
        <ul>
            <li>
                id | 标题 | 创建时间 | 更新时间 | <input type="text" id="search">
                <button onclick="search();">search</button>
            </li>
            {% for i in artic_content %}
                <li>
                    <a href="#">{{ i.title }}</a> | {{ i.create_date }} | {{ i.update_date }}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
<script>
    var ipt = document.getElementById('search')

    function search() {
        let a = document.createElement('a')
        console.log(ipt.value)
        a.href = `{% url 'App:main_app' id=id %}?search=${ipt.value}`
        console.log(a)
        a.click()
    }

</script>
</body>
</html>

python/python_web/djangoProject/templates/main_app2.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>main_app2</title>
</head>
<body>
<h2>MAIN_APP2</h2>
<input type=”text” aria-label=”用户名”/>

</body>
</html>

python/python_web/djangoProject/templates/mycache.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ app }}
</body>
</html>

python/python_web/djangoProject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
<form action="{% url 'APP03:register' %}" method="post">
    {% csrf_token %}
    用户名 <input type="text" name="username">
    {% for error in form.username.errors %}
        {{ error }}
    {% endfor %}

    <br>
    密码 <input type="text" name="password">
    {% for error in form.password.errors %}
        {{ error }}
    {% endfor %} <br>
    确认密码 <input type="text" name="confirm">
    {% for error in form.confirm.errors %}
        {{ error }}
    {% endfor %} <br>
    性别
    <input type="radio" name="sex" value="0">女
    <input type="radio" name="sex" value="1">男
    {% for error in form.sex.errors %}
        {{ error }}
    {% endfor %}
    <br>
    手机 <input type="text" name="mobile">
    {% for error in form.mobile.errors %}
        {{ error }}
    {% endfor %}<br>
    时间 <input type="date" name="regtime">
    {% for error in form.regtime.errors %}
        {{ error }}
    {% endfor %} <br>
{#    验证码 <input type="input" name="captcha">#}
{#    <img src="{{ image_url }}" alt="">#}
{#    {% for error in form.captcha.errors %}#}
{#        {{ error }}#}
{#    {% endfor %} <br>#}
    <input type="submit" value="注册">
</form>


{% for field in form %}
    {% for error in field.errors %}
        {{ error }}
    {% endfor %}
{% endfor %}


{% for field in form.visible_fields %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
{% endfor %}
</body>
</html>

python/python_web/djangoProject/templates/uploads.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'APP03:uploads' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="fafafa">
        <input type="submit">
    </form>
</body>
</html>